### PR TITLE
Display syllabi by semesters

### LINKED ISSUE #25: Add semester field to uploads / filter by semester
We can make this happen and only show the most recent syllabi for each course/prof, with the option of seeing earlier submissions. Would involve adding a field to submission model for semester/year.

### PR DESCRIPTION
**Pull request by winstliu**
It seems _so, so_ inefficient to do it like this but it has been a long day and I was working on this as a distraction.

So please tell me how to do this in a more Django-esque way, and I will also try to sleep on it tonight.

### CODE REVIEW

**Comment by verndrade** [comment]
we can maybe do something like display the most recent syllabus at first when you click on the class but have buttons for previous semesters appear if previous semesters exist.

Or when you click the class it gives a breakdown of the class and buttons for all previous semesters

**Comment by winstliu** [comment]
Yeah I'm not done with the UI yet, was more talking about the Python side of things. I haven't been able to concentrate on this  because...well...current events. I'll have more at a later time.

**Comment by verndrade** [comment]
100% understand I've been putting this on the backburner bc of current events too.

**Comment by winstliu** [comment]
We're gonna do this from scratch.

**Pull request closed without merging**
