### PR TITLE
Improving UI/UX and accessibility

### LINKED ISSUE #61: Back Button Navigator should not be at bottom of left
The placement seems off to me. And it is too prominent.

### PR DESCRIPTION
**Pull request by mengsarah**
I was looking through the branches list and I saw `some-accessibility` and I was like huh, didn't I delete that?

Turns out my previous pull request's branch was also named `UI-improvement`, which means I actually deleted `UI-improvement` and started `some-accessibility` but then left it alone for so long that I forgot `some-accessibility` is the new branch. Cue facepalm... I should probably adopt some kind of branch naming scheme.

Stuff done, updated June 26, 2020:
- accessibility stuff in #75 
- signup page errors to top of page
- resolve #61 🔥 with the browse button and breadcrumbs
- confirmation message fixed by checking for messages everywhere (in `base.html` and its deprecated version)
- typos and weird capitalization and explanation of deletion
- maybe some other stuff

### CODE REVIEW

**Comment by winstliu** [comment]
> making use of the C in CSS

😂

**Comment by mengsarah** [comment]
> 
> 
> > making use of the C in CSS
> 
> 😂

😜 

Merged `development` into this branch to work with all the stuff that's already done.

I present to you breadcrumbs! Suggested in #61. Picked some compliant colors for now because the defaults did not mesh well at all with our background, but I know nothing about breadcrumb styling.

image

image


And after much agony, I figured out where the sign up error messages were hiding and brought them up (they're still next to the relevant form elements, too):

image

I manually styled that box so that it matches the one that can appear on the login page. Speaking of that, we now have two error message styles. 😅

**Comment by mengsarah** [comment]
Okay, I think that's all for now!

**Review by verndrade — APPROVED** [review]
Great Work! It looks awesome!

**Pull request merged**
