### PR TITLE
Better auth

### LINKED ISSUE #16: Add more login methods
Allow alternate log in methods for universities who don't use GSuite, such as Shibboleth.

### PR DESCRIPTION
**Pull request by verndrade**
Changes login scheme to one that would work for all emails.

### CODE REVIEW

**Comment by winstliu** [comment]
My current plan is to bring in crispy-forms. crispy-forms and I have a love-hate (edit: actually, more like hate-hate) relationship but you can't deny that they do make forms look great.

**Comment by winstliu** [comment]
Needs at the minimum a separate template for the pages that you can access while logged out, and then extra UI work on top of that.

**Comment by winstliu** [comment]
Current status, inspiration from GitHub and theCourseForum. I'll need to figure out how to fill in all that empty space, then work on the signup, login, and about pages, and then do an accessibility pass (hopefully w/ @mengsarah to point out any mistakes I overlook 🙈).

landing-page

**Comment by winstliu** [comment]
Okay, this is almost ready, I think. It definitely needs password reset before we can ship, but I should be able to yoink that code from Satori pretty easily. Spam protection would also be a plus, but I don't want to work on that before coming to an agreement on what that should entail.

Here's the current UI and signup/login flow as of tonight.

Initial impression (still pretty empty):
landing

***

Full signup page (if you choose not to sign up from the landing page):
signup-full

***

After signing up:
confirmation-required

***

Login attempt without confirming:
unconfirmed-account

***

After clicking the confirmation link (teal!):
confirmation-successful

**Comment by verndrade** [comment]
damn winston go off! it looks great

**Comment by winstliu** [comment]
I think all this needs before it can be merged is a proper marketing pass on the landing page and accessibility checks, and everything else can be adjusted later.

**Comment by verndrade** [comment]
ok i made some ui changes. 
now the drop down username will only be everything before the '@' and theres a bit more padding for the signup form. I ran through a couple log in / confirm / forget password scenarios and it seems good!

**Comment by mrf7pc** [comment]
This is AMAZING, great work!! Approved! But I think we're waiting to merge until others approve.

**Review by mrf7pc — APPROVED** [review]

**Pull request merged**
