### PR TITLE
Change footer styles

### PR DESCRIPTION
**Pull request by winstliu**
As hashed out in Slack.

### CODE REVIEW

**Comment by winstliu** [comment]
image

**Comment by mengsarah** [comment]
There's some horizontal scrolling with big text. I can try to fix that

The footer's top border color bothers me against the blue bg when we're logged in but that's minor

**Review by mengsarah — APPROVED** [review]
I think I'm doing this reviewing thing right

**Comment by winstliu** [comment]
> The footer's top border color bothers me against the blue bg when we're logged in but that's minor

Same 😥

**Pull request merged**
